from typing import Optional

from pydantic import BaseModel, ConfigDict, Field


class Media(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    mediaType: str
    live: bool
    streamURL: Optional[str] = Field(default=None)
    eventStreamURL: Optional[str] = Field(default=None)
    downloadURL: Optional[str] = Field(default=None)
    thumbnailImageURL: Optional[str] = Field(default=None)
    bitrate: Optional[int]
    fileSizeBytes: Optional[int] = Field(default=None)
    adaptiveBitrate: bool
    duration: Optional[int] = Field(default=None)
    audioCodec: Optional[str] = Field(default=None)
    videoCodec: Optional[str] = Field(default=None)
    language: Optional[str] = Field(default=None)
    mediaFilename: str
    autoGenerated: Optional[bool] = Field(default=None)


class MediaSet(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    audio: list[Media]
    video: list[Media]
    text: list[Media]
    caption: list[Media]


class LiteSermonSeries(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    id: int = Field(alias="seriesID")


class LiteSermonSpeaker(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    id: int = Field(alias="speakerID")
    displayName: Optional[str] = Field(default=None)
    portaitURL: Optional[str] = Field(default=None)
    albumArtURL: Optional[str] = Field(default=None)
    roundedThumbnailImageURL: Optional[str] = Field(default=None)
    portraitURLResizable: Optional[str] = Field(default=None)
    roundedThumbnailImageURLResizable: Optional[str] = Field(default=None)


class Speaker(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    id: int = Field(alias="speakerID")
    displayName: Optional[str] = Field(default=None)
    portaitURL: Optional[str] = Field(default=None)
    albumArtURL: Optional[str] = Field(default=None)
    roundedThumbnailImageURL: Optional[str] = Field(default=None)
    portraitURLResizable: Optional[str] = Field(default=None)
    roundedThumbnailImageURLResizable: Optional[str] = Field(default=None)
    sortName: Optional[str] = Field(default=None)
    bio: Optional[str] = Field(default=None)


class Broadcaster(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    lite_type: str
    id: str = Field(alias="broadcasterID")
    displayName: str
    location: str
    imageURL: str
    imageURLResizable: str
    languageCode: str
    shortName: str
    homePageURL: str
    albumArtURL: str
    listenLineNumber: Optional[str] = Field(default=None)
    categories: int
    welcomeVideoID: Optional[str] = Field(default=None)
    disabled: bool
    groups: Optional[list[str]] = Field(default_factory=list)
    bannerImageURL: str


class Sermon(BaseModel):
    model_config = ConfigDict(extra="ignore")

    id: str = Field(alias="sermonID")
    fullTitle: str
    displayTitle: str
    languageCode: str
    bibleText: Optional[str] = Field(default=None)
    subtitle: Optional[str] = Field(default=None)
    moreInfoText: Optional[str] = Field(default=None)
    eventType: str
    broadcaster: Broadcaster
    speaker: LiteSermonSpeaker
    series: Optional[LiteSermonSeries] = Field(default=None)
    hasAudio: bool
    hasVideo: bool
    hasPDF: bool
    audioDurationSeconds: Optional[int] = Field(default=None)
    videoDurationSeconds: Optional[int] = Field(default=None)
    preachDate: str
    publishTimestamp: int
    type: str
    updateDate: Optional[int] = Field(default=None)
    publishDate: str
    displayEventType: str
    externalLink: Optional[str] = Field(default=None)
    media: MediaSet
    waveformPeaksURL: str
    keywords: Optional[str] = Field(default=None)


class Series(BaseModel):
    model_config = ConfigDict(extra="ignore")

    type: str
    id: int = Field(alias="seriesID")
    title: str
    broadcasterID: str
    latest: Optional[str] = Field(default=None)
    earliest: Optional[str] = Field(default=None)
    updated: Optional[int] = Field(default=None)
    count: int
    description: Optional[str] = Field(default=None)
    podcastEnabled: Optional[bool] = Field(default=None)
    podcaseSpeaker: Optional[str] = Field(default=None)
    image: Optional[str] = Field(default=None)
    imageResizable: Optional[str] = Field(default=None)
    defaultSortBy: Optional[str] = Field(default=None)
